base:
  is_debug:
  domain:
  max_concurrency:

http:
  port:

mysql:
  username:
  password:
  host:
  port:
  dbname:
  charset:

mongodb:
  dsn:
  database:
  pool_size:

jwt:
  issuer:
  secret:


clients:
  runner:
    run_api:
    run_scene:
    stop_scene:
    run_plan:
    stop_plan:

proof:
  info_log:
  err_log:

log:
  InfoPath:
  ErrPath:

redis:
  # 集群地址 使用;分割 例如 127.0.0.1:7000;127.0.0.1:7001;127.0.0.1:7002;127.0.0.1:7003;127.0.0.1:7004;127.0.0.1:7005
  clusterAddress : ""
  password: ""

#redisReport:
#  clusterAddress: "10.125.164.226:32755"
#  password: "tianQ#V587"
#  db: 0

smtp:
  host:
  port:
  email:
  password:

sms:
  id:
  secret:

inviteData:
  AesSecretKey:

#初始化压力机可使用分区
canUsePartitionTotalNum: 2

#单台压力机能快速负载的并发数
oneMachineCanConcurrenceNum: 5000

#运行计划相关配置
machineConfig:
  MachineAliveTime: 10      # 压力机上报心跳超时时间，单位：秒
  InitPartitionTotalNum: 2  # 初始化可用kafka分区数量设置
  CpuTopLimit: 65           # 可参与压测的压力机cpu使用率上限
  MemoryTopLimit: 65        # 可参与压测的压力机memory使用率上限
  DiskTopLimit: 55          # 可参与压测的压力机disk使用率上限
